In [47]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

# Load dataset
csv_file = '/content/laptopData.csv'
df = pd.read_csv(csv_file)

# Select numeric columns
laptop_data = df.select_dtypes(include=[np.number])
laptop_data_mm=laptop_data

# Impute missing values with median
imputer = SimpleImputer(strategy='median')
laptop_data_clean = imputer.fit_transform(laptop_data)

# Create new DataFrame with cleaned data
laptop_data_clean_df = pd.DataFrame(laptop_data_clean, columns=laptop_data.columns)

# Encode categorical data
laptop_categorical = df[["Gpu"]]
ordinal_encoder = OrdinalEncoder()
laptop_cat_encoded = ordinal_encoder.fit_transform(laptop_categorical)
df.head(10)



Unnamed: 0 Company   TypeName Inches                    ScreenResolution  \
0         0.0   Apple  Ultrabook   13.3  IPS Panel Retina Display 2560x1600   
1         1.0   Apple  Ultrabook   13.3                            1440x900   
2         2.0      HP   Notebook   15.6                   Full HD 1920x1080   
3         3.0   Apple  Ultrabook   15.4  IPS Panel Retina Display 2880x1800   
4         4.0   Apple  Ultrabook   13.3  IPS Panel Retina Display 2560x1600   
5         5.0    Acer   Notebook   15.6                            1366x768   
6         6.0   Apple  Ultrabook   15.4  IPS Panel Retina Display 2880x1800   
7         7.0   Apple  Ultrabook   13.3                            1440x900   
8         8.0    Asus  Ultrabook     14                   Full HD 1920x1080   
9         9.0    Acer  Ultrabook     14         IPS Panel Full HD 1920x1080   

                          Cpu   Ram               Memory  \
0        Intel Core i5 2.3GHz   8GB            128GB SSD   
1        Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2  Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3        Intel Core i7 2.7GHz  16GB            512GB SSD   
4        Intel Core i5 3.1GHz   8GB            256GB SSD   
5     AMD A9-Series 9420 3GHz   4GB            500GB HDD   
6        Intel Core i7 2.2GHz  16GB  256GB Flash Storage   
7        Intel Core i5 1.8GHz   8GB  256GB Flash Storage   
8  Intel Core i7 8550U 1.8GHz  16GB            512GB SSD   
9  Intel Core i5 8250U 1.6GHz   8GB            256GB SSD   

                            Gpu       OpSys  Weight        Price  
0  Intel Iris Plus Graphics 640       macOS  1.37kg   71378.6832  
1        Intel HD Graphics 6000       macOS  1.34kg   47895.5232  
2         Intel HD Graphics 620       No OS  1.86kg   30636.0000  
3            AMD Radeon Pro 455       macOS  1.83kg  135195.3360  
4  Intel Iris Plus Graphics 650       macOS  1.37kg   96095.8080  
5                 AMD Radeon R5  Windows 10   2.1kg   21312.0000  
6       Intel Iris Pro Graphics    Mac OS X  2.04kg  114017.6016  
7        Intel HD Graphics 6000       macOS  1.34kg   61735.5360  
8          Nvidia GeForce MX150  Windows 10   1.3kg   79653.6000  
9        Intel UHD Graphics 620  Windows 10   1.6kg   41025.6000

In [48]:
from sklearn.preprocessing import LabelEncoder
label_encode=LabelEncoder()
housing_cat_label=label_encode.fit_transform(laptop_categorical)
print(housing_cat_label)


[58 51 53 ... 40 21 40]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [49]:
from sklearn.preprocessing import LabelEncoder
label_encode = LabelEncoder()
# If housing_categorical is a DataFrame or a 2D array, convert it to a 1D array
laptop_categorical = laptop_categorical.values.ravel() if hasattr(laptop_categorical, 'values') else laptop_categorical.ravel()
laptop_cat_label = label_encode.fit_transform(laptop_categorical)
print(laptop_cat_label.tolist())

[58, 51, 53, 9, 59, 17, 60, 51, 98, 61, 53, 47, 10, 24, 52, 58, 24, 11, 72, 61, 110, 75, 12, 61, 53, 47, 51, 7, 61, 69, 40, 12, 7, 61, 51, 43, 53, 7, 53, 70, 53, 79, 72, 61, 63, 56, 110, 37, 24, 66, 110, 98, 16, 61, 53, 6, 47, 53, 80, 47, 7, 61, 53, 61, 53, 76, 6, 41, 53, 76, 53, 7, 7, 75, 47, 75, 53, 61, 97, 69, 61, 52, 53, 5, 17, 76, 85, 53, 79, 61, 36, 98, 61, 79, 53, 61, 24, 24, 65, 75, 7, 12, 6, 98, 53, 72, 47, 72, 76, 53, 98, 58, 53, 61, 61, 110, 61, 72, 66, 72, 53, 80, 72, 70, 17, 110, 61, 12, 7, 61, 30, 24, 61, 97, 53, 61, 43, 75, 66, 53, 97, 35, 77, 47, 16, 61, 46, 43, 110, 47, 75, 75, 53, 79, 53, 6, 53, 53, 61, 47, 22, 98, 6, 76, 43, 79, 44, 75, 98, 61, 53, 6, 16, 53, 69, 53, 47, 62, 4, 61, 7, 61, 61, 53, 98, 63, 75, 75, 52, 7, 110, 43, 98, 98, 61, 69, 82, 61, 75, 70, 79, 47, 72, 79, 101, 79, 53, 61, 61, 110, 75, 75, 47, 53, 53, 7, 85, 69, 61, 61, 6, 61, 47, 61, 79, 72, 30, 67, 86, 1, 53, 12, 79, 53, 47, 30, 47, 24, 82, 75, 47, 63, 86, 75, 53, 7, 53, 82, 61, 59, 61, 93, 22, 6

In [50]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
laptop_num_std_scaled = std_scaler.fit_transform(laptop_data)
laptop_num_std_scaled

array([[-1.73424537,  0.30609883],
       [-1.73158823, -0.32317983],
       [-1.7289311 , -0.78568359],
       ...,
       [ 1.72003084, -1.2796834 ],
       [ 1.72268798, -0.51583976],
       [ 1.72534511, -1.07979908]])

In [51]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler(feature_range=(-1, 1))
laptop_Scaled = min_max_scaler.fit_transform(laptop_data_mm)
laptop_Scaled

array([[-1.        , -0.60651814],
       [-0.9984639 , -0.75529451],
       [-0.9969278 , -0.86464135],
       ...,
       [ 0.9969278 , -0.9814346 ],
       [ 0.9984639 , -0.80084388],
       [ 1.        , -0.93417722]])

In [52]:
print(laptop_data_mm.dtypes)


Unnamed: 0    float64
Price         float64
dtype: object


In [69]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Extract the price data
price_data = laptop_data_mm[['Price']].to_numpy()

# Remove nan values from price_data
price_data = price_data[~np.isnan(price_data)]

# Check if there's data left after removing nan values
if price_data.shape[0] > 0:
    # Calculate Q1, Q3, and IQR
    Q1 = np.percentile(price_data, 25, axis=0)
    Q3 = np.percentile(price_data, 75, axis=0)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Filter out outliers based on IQR
    mask = (price_data >= lower_bound) & (price_data <= upper_bound)
    price_data_no_outliers = price_data[mask]

    # Ensure there's data to scale
    if price_data_no_outliers.shape[0] > 0:
        min_max_scaler = MinMaxScaler(feature_range=(-1, 1))

        # Reshape price_data_no_outliers to a 2D array
        price_data_no_outliers = price_data_no_outliers.reshape(-1, 1)

        laptop_scaled = min_max_scaler.fit_transform(price_data_no_outliers)
        print("Q1:", Q1)
        print("Q3:", Q3)
        print("IQR:", IQR)
        print(laptop_scaled)
    else:
        print("No data left after outlier removal.")
else:
    print("No data left after removing nan values.")

Q1: 31914.72
Q3: 79333.3872
IQR: 47418.667199999996
[[-0.11681788]
 [-0.45075102]
 [-0.69618335]
 ...
 [-0.95832939]
 [-0.55298797]
 [-0.85225874]]
