In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

In [ ]:
csv_file='/content/drive/MyDrive/Colab Notebooks/housing.csv'
df = pd.read_csv(csv_file)

In [ ]:
null_values=df['total_bedrooms'].isnull().sum()
print(null_values)

207


In [ ]:
#df.dropna(subset=["total_bedrooms"], inplace=True) Option 1

#df.drop("total_bedrooms", axis=1) Option 2

median = df["total_bedrooms"].median() # option 3
df["total_bedrooms"].fillna(median, inplace=True)


In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')


In [ ]:
housing_data=df.select_dtypes(include=[np.number])


In [ ]:
imputer.fit(housing_data)


SimpleImputer(strategy='median')

In [ ]:
imputer.statistics_
housing_data.median().values

array([-1.1849e+02,  3.4260e+01,  2.9000e+01,  2.1270e+03,  4.3500e+02,
        1.1660e+03,  4.0900e+02,  3.5348e+00,  1.7970e+05])

In [ ]:
X=imputer.transform(housing_data)
print(X)

[[-1.2223e+02  3.7880e+01  4.1000e+01 ...  1.2600e+02  8.3252e+00
   4.5260e+05]
 [-1.2222e+02  3.7860e+01  2.1000e+01 ...  1.1380e+03  8.3014e+00
   3.5850e+05]
 [-1.2224e+02  3.7850e+01  5.2000e+01 ...  1.7700e+02  7.2574e+00
   3.5210e+05]
 ...
 [-1.2122e+02  3.9430e+01  1.7000e+01 ...  4.3300e+02  1.7000e+00
   9.2300e+04]
 [-1.2132e+02  3.9430e+01  1.8000e+01 ...  3.4900e+02  1.8672e+00
   8.4700e+04]
 [-1.2124e+02  3.9370e+01  1.6000e+01 ...  5.3000e+02  2.3886e+00
   8.9400e+04]]


In [ ]:
housing_tr = pd.DataFrame(X, columns=housing_data.columns,
index=housing_data.index)

print(housing_tr)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  media

In [ ]:
housing_categorical=df[["ocean_proximity"]]
housing_categorical.head(500)

ocean_proximity
0          NEAR BAY
1          NEAR BAY
2          NEAR BAY
3          NEAR BAY
4          NEAR BAY
..              ...
495          INLAND
496       <1H OCEAN
497       <1H OCEAN
498       <1H OCEAN
499      NEAR OCEAN

[500 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_categorical)

In [ ]:
housing_cat_encoded[:200]

array([[3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],

In [ ]:
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

#**OneHot Encoder**

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
cat_encoder=OneHotEncoder()
housing_cat_1hot=cat_encoder.fit_transform(housing_categorical)
housing_cat_1hot
print(housing_cat_1hot)
#sparse matrix representation (i, j) 1.0:
#This notation means that the element at the i-th row and j-th column of the matrix has a value of 1.0.
#All other elements in that row are 0.
#You can imagine it like (0,3)=[0,0,0,1]

  (0, 3)	1.0
  (1, 3)	1.0
  (2, 3)	1.0
  (3, 3)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 3)	1.0
  (7, 3)	1.0
  (8, 3)	1.0
  (9, 3)	1.0
  (10, 3)	1.0
  (11, 3)	1.0
  (12, 3)	1.0
  (13, 3)	1.0
  (14, 3)	1.0
  (15, 3)	1.0
  (16, 3)	1.0
  (17, 3)	1.0
  (18, 3)	1.0
  (19, 3)	1.0
  (20, 3)	1.0
  (21, 3)	1.0
  (22, 3)	1.0
  (23, 3)	1.0
  (24, 3)	1.0
  :	:
  (20615, 1)	1.0
  (20616, 1)	1.0
  (20617, 1)	1.0
  (20618, 1)	1.0
  (20619, 1)	1.0
  (20620, 1)	1.0
  (20621, 1)	1.0
  (20622, 1)	1.0
  (20623, 1)	1.0
  (20624, 1)	1.0
  (20625, 1)	1.0
  (20626, 1)	1.0
  (20627, 1)	1.0
  (20628, 1)	1.0
  (20629, 1)	1.0
  (20630, 1)	1.0
  (20631, 1)	1.0
  (20632, 1)	1.0
  (20633, 1)	1.0
  (20634, 1)	1.0
  (20635, 1)	1.0
  (20636, 1)	1.0
  (20637, 1)	1.0
  (20638, 1)	1.0
  (20639, 1)	1.0


In [ ]:
housing_cat_1hot.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [ ]:
cat_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [ ]:
df_test = pd.DataFrame({"ocean_proximity": ["INLAND", "NEAR BAY"]})
pd.get_dummies(df_test)

ocean_proximity_INLAND  ocean_proximity_NEAR BAY
0                    True                     False
1                   False                      True

In [ ]:
cat_encoder.transform(df_test).toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
df_test_unknown = pd.DataFrame({"ocean_proximity": ["<2H OCEAN","ISLAND"]})
pd.get_dummies(df_test_unknown)
cat_encoder.handle_unknown = "ignore"
cat_encoder.transform(df_test_unknown).toarray()

array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

#**Label Encoding**#


In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encode=LabelEncoder()
housing_cat_label=label_encode.fit_transform(housing_categorical)
print(housing_cat_label)


[3 3 3 ... 1 1 1]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encode = LabelEncoder()
# If housing_categorical is a DataFrame or a 2D array, convert it to a 1D array
housing_categorical = housing_categorical.values.ravel() if hasattr(housing_categorical, 'values') else housing_categorical.ravel()
housing_cat_label = label_encode.fit_transform(housing_categorical)
print(housing_cat_label.tolist())


[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 1, 4, 0, 0, 0, 4, 0, 0, 0, 1, 4, 0, 0, 4, 0, 3, 1, 1, 4, 0, 4, 3, 4, 0, 4, 0, 1, 0, 3, 0, 1, 4, 0, 3, 0, 1, 4, 0, 1, 1, 0, 1, 1, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 4, 4, 0, 1, 4, 1, 0, 1, 3, 0, 1, 1, 4, 1, 1, 0, 4, 0, 4, 1, 0, 0, 4, 4, 1, 0, 0, 0, 4, 0, 0, 0, 0, 1, 0, 3, 1, 0, 4, 1, 3, 3, 0, 1, 0, 0, 1, 0, 0, 1, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 3, 3, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 3, 1, 3, 1, 0, 1, 0, 1, 0, 4, 0, 4, 1, 0, 0, 0, 0, 1, 1, 0, 4, 0, 0, 3, 1, 0, 0, 1, 0, 0, 4, 0, 4, 1, 0, 0, 0, 4, 1, 0, 0, 1, 1, 0, 3, 3, 4, 1, 3, 0, 1, 1, 0, 0, 0, 0, 4, 0, 1, 0, 1, 0, 0, 1, 4, 4, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 3, 1, 1, 1, 1, 4, 1, 0, 0, 0, 4, 0, 3, 0, 1, 0, 1, 1, 1, 3, 